### ISSUE TITLE
Don`t work in Windows

### ISSUE THREAD

**Issue by objectprogr** [andrewning/sortphotos#109]
I try using this on Windows, but dosn`t work.
Do I mus`t install this script some or download repo and use script on cmd?
If I open repo in cmd and I try execute script I have this errors:
`python sortphotos.py \Users\xxxx\Desktop\test\ \Users\xxx\Desktop\dest\
Traceback (most recent call last):
  File "sortphotos.py", line 502, in <module>
    main()
  File "sortphotos.py", line 499, in main
    args.use_only_tags, not args.silent, args.keep_filename)
  File "sortphotos.py", line 303, in sortPhotos
    with ExifTool(verbose=verbose) as e:
  File "sortphotos.py", line 194, in __enter__
    stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The specified file can not be found`

If I use this path:
`python sortphotos.py \\Users\\xxx\\Desktop\\test \\Users\\xxx\\Desktop\\dest
Traceback (most recent call last):
  File "sortphotos.py", line 502, in <module>
    main()
  File "sortphotos.py", line 499, in main
    args.use_only_tags, not args.silent, args.keep_filename)
  File "sortphotos.py", line 275, in sortPhotos
    raise Exception('Source directory does not exist')
Exception: Source directory does not exist`

If I use Python2:
`python2 sortphotos.py \\Users\\xxx\\Desktop\\test \\Users\\xxx\\Desktop\\dest
Traceback (most recent call last):
  File "sortphotos.py", line 502, in <module>
    main()
  File "sortphotos.py", line 499, in main
    args.use_only_tags, not args.silent, args.keep_filename)
  File "sortphotos.py", line 275, in sortPhotos
    raise Exception('Source directory does not exist')
Exception: Source directory does not exist`
You can help me?

**Comment by Morelatto** [comment]
In my case the first error was solved by installing Perl. I'm using python-3.7.0-x64.

**Comment by tplive** [comment]
I'm having the same issue. @Morelatto, can you please elaborate on the fix? How does installing Perl help? Is Perl a prerequisite for this script? Shouldn't the setup program install or even check for Perl then? :)

**Comment by Sillium007** [comment]
The script uses runs exiftool to get the informations from the pictures. And exiftool is written in perl: https://github.com/andrewning/sortphotos/blob/master/src/Image-ExifTool/exiftool

I was annoyed by this and changed the script to use an exe file instead of the perl script.

**Comment by objectprogr** [comment]
I had a trouble with perl. Reinstall perl solve my problem. Thank you!

**Comment by andrewning** [comment]
I added a note in the README to mention the perl dependency.
