### ISSUE TITLE
(Fix) File name with German character umlaut causes unicodedecode error

### ISSUE THREAD

**Issue by denisgaebler** [andrewning/sortphotos#120]
Hi,

I added the following code at the beginning of sortphotos.py after locale:
reload(sys)
sys.setdefaultencoding("utf-8")
And this fixed the issue with the file name containing an 'ä' character.
Locale is de_DE.UTF8, so the locale call does not help here. The error happens during join of the target filename and the exception itself is in posixpath.py.
I got the fix from:
https://pydio.com/forum/f/topic/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3/

Thanks, Denis.

**Comment by jo3rg** [comment]
I can verify that this solution works for me too, can we add this change to the codebase?
Thanks and regards

**Comment by cokron** [comment]
I had the same issue. I changed all `%Y/%m-%b` to `%Y/%m` in `src/sortphotos.py`, because I don't care for "03-Mär" anyway and prefer "03". 

```
Traceback (most recent call last):
  File "/Users/cokron/.asdf/installs/python/2.7.15/bin/sortphotos", line 11, in <module>
    load_entry_point('sortphotos==1.0', 'console_scripts', 'sortphotos')()
  File "/Users/cokron/.asdf/installs/python/2.7.15/lib/python2.7/site-packages/sortphotos-1.0-py2.7.egg/src/sortphotos.py", line 499, in main
    args.use_only_tags, not args.silent, args.keep_filename)
  File "/Users/cokron/.asdf/installs/python/2.7.15/lib/python2.7/site-packages/sortphotos-1.0-py2.7.egg/src/sortphotos.py", line 377, in sortPhotos
    dest_file = os.path.join(dest_file, filename)
  File "/Users/cokron/.asdf/installs/python/2.7.15/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
```
