### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by Transantarctica** [andrewning/sortphotos#127]
I'm encountering a problem with the inputting the folder/files on Windows 10 with python3. Tried the same on Ubuntu 20.04, worked there.

```
C:\Users\User\Scripts\sortphotos\src>python sortphotos.py -r --sort %Y/%m C:\Users\User\Desktop\Btrx\ C:\Users\User\Desktop\resultset
Traceback (most recent call last):
  File "sortphotos.py", line 502, in <module>
    main()
  File "sortphotos.py", line 499, in main
    args.use_only_tags, not args.silent, args.keep_filename)
  File "sortphotos.py", line 303, in sortPhotos
    with ExifTool(verbose=verbose) as e:
  File "sortphotos.py", line 194, in __enter__
    stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Program Files\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden (The system cannot find the specified file)
```

Don't know if it's about the source or destination directory, but I guess the following is unrelated.
```
C:\Users\User\Scripts\sortphotos\src>python sortphotos.py -r --sort %Y/%m C:\Users\User\Desktop\Btrx\
usage: sortphotos.py [-h] [-r] [-c] [-s] [-t] [--sort SORT] [--rename RENAME]
                     [--keep-filename] [--keep-duplicates]
                     [--day-begins DAY_BEGINS]
                     [--ignore-groups IGNORE_GROUPS [IGNORE_GROUPS ...]]
                     [--ignore-tags IGNORE_TAGS [IGNORE_TAGS ...]]
                     [--use-only-groups USE_ONLY_GROUPS [USE_ONLY_GROUPS ...]]
                     [--use-only-tags USE_ONLY_TAGS [USE_ONLY_TAGS ...]]
                     src_dir dest_dir
sortphotos.py: error: the following arguments are required: dest_dir
```

**Comment by Transantarctica** [comment]
I guess it was about Perl not being installed.
