### ISSUE TITLE
TypeError: Can't mix strings and bytes in path components (#92) still persists

### ISSUE THREAD

**Issue by scotws** [andrewning/sortphotos#138]
Error #92 seems to have been prematurely closed, as it persists with my current Ubuntu 20.04 LTS setup (Python 3.8.5):

```
[1/19913] (TEST - no files are being moved/copied)
Source: Possum iPhoto All/IMG_1115.JPG.jpg
Date/Time: 2009-04-21 17:28:23
Corresponding Tags: EXIF:ModifyDate, EXIF:DateTimeOriginal, EXIF:CreateDate, XMP:CreateDate, XMP:ModifyDate, XMP:DateCreated
Traceback (most recent call last):
  File "/usr/local/bin/sortphotos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/src/sortphotos.py", line 498, in main
    sortPhotos(args.src_dir, args.dest_dir, args.sort, args.rename, args.unknown_dir, args.recursive, 
  File "/usr/local/lib/python3.8/dist-packages/src/sortphotos.py", line 376, in sortPhotos
    dest_file = os.path.join(dest_file, filename.encode('utf-8'))
  File "/usr/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.8/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by ShuffleBit** [comment]
I don't think it will be updated. I doubt a PR will be answered. But you can fix this yourself:
Line 376 of /usr/local/lib/python3.8/dist-packages/src/sortphotos.py
Original:
`dest_file = os.path.join(dest_file, filename.encode('utf-8'))`
which converts the str to byte for whatever the reason
Fixed:
`dest_file = os.path.join(dest_file, filename)`
