### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified - subprocess - tid = _winapi.CreateProcess(executable, args

### ISSUE THREAD

**Issue by Dedale42** [andrewning/sortphotos#159]
```
C:\Users\Me\Documents\code_files\sortphotos-master\src>python sortphotos.py C:\Users\Me\Pictures\Photo C:\Users\Me\Pictures\Photobydate --rename %Y_%m%d_%H%M
Traceback (most recent call last):
  File "C:\Users\Me\Documents\code_files\sortphotos-master\src\sortphotos.py", line 503, in <module>
    main()
  File "C:\Users\Me\Documents\code_files\sortphotos-master\src\sortphotos.py", line 497, in main
    sortPhotos(args.src_dir, args.dest_dir, args.sort, args.rename, args.recursive,
  File "C:\Users\Me\Documents\code_files\sortphotos-master\src\sortphotos.py", line 304, in sortPhotos
    with ExifTool(verbose=verbose) as e:
  File "C:\Users\Me\Documents\code_files\sortphotos-master\src\sortphotos.py", line 193, in __enter__
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\scoop\apps\python\current\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Me\scoop\apps\python\current\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Run into this error any clue

**Comment by Sillium007** [comment]
It tries to start ExifTool. Seems like you don't have it installed or at least not installed where it is expected to be.
