### ISSUE TITLE
Crash invalid XMP:GPSDateTime

### ISSUE THREAD

**Issue by egallen** [andrewning/sortphotos#35]
For some pictures took with a Sony DSC-HX20V, day = int(date_entries[2]) failed in sortphotos.py

fix, replace:
```
day = int(date_entries[2]) 
```
by
```
day = int(float(date_entries[2]))
```

```
$ python sortphotos.py --sort '%Y-%m-%d'  -r inputfolder outputfolder
Preprocessing with ExifTool.  May take a while for a large number of files.
    1 directories scanned
    1 image files read
[{
  "SourceFile": "/home/inputfolder/bug.JPG",
  "File:FileModifyDate": "2014:09:14 10:01:34+02:00",
  "File:FileAccessDate": "2015:01:02 18:05:15+01:00",
  "File:FileInodeChangeDate": "2015:01:02 18:05:14+01:00",
  "EXIF:ModifyDate": "2014:09:14 10:01:28",
  "EXIF:DateTimeOriginal": "2014:09:13 16:03:05",
  "EXIF:CreateDate": "2014:09:13 16:03:05",
  "MakerNotes:SonyDateTime": "",
  "EXIF:GPSTimeStamp": "14:03:06",
  "EXIF:GPSDateStamp": "2014:09:13",
  "XMP:DateTimeOriginal": "2014:09:13 16:03:05",
  "XMP:DateTimeDigitized": "2014:09:13 16:03:05",
  "XMP:GPSDateTime": "14:03:06.00",
  "Composite:GPSDateTime": "2014:09:13 14:03:06Z"
}]
{ready}

Traceback (most recent call last):
  File "sortphotos.py", line 474, in <module>
    args.use_only_tags, not args.silent)
  File "sortphotos.py", line 304, in sortPhotos
    src_file, date, keys = get_oldest_timestamp(data, additional_groups_to_ignore, additional_tags_to_ignore)
  File "sortphotos.py", line 139, in get_oldest_timestamp
    exifdate = parse_date_exif(date)
  File "sortphotos.py", line 47, in parse_date_exif
    day = int(date_entries[2])
ValueError: invalid literal for int() with base 10: '06.00'
```

Cheers
_____
```
$ python --version
Python 2.7.6
$ uname -a
Darwin redux.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
```
______
```
$ python EXIF.py bug.JPG 
Opening: bug.JPG
File has JPEG thumbnail
EXIF DateTimeDigitized (ASCII): 2014:09:13 16:03:05
EXIF DateTimeOriginal (ASCII): 2014:09:13 16:03:05
EXIF GPS GPSAltitude (Ratio): 88/8
EXIF GPS GPSAltitudeRef (Byte): 0
EXIF GPS GPSDOP (Ratio): 8/8
EXIF GPS GPSDate (ASCII): 2014:09:13
EXIF GPS GPSDifferential (Short): 0
EXIF GPS GPSImgDirection (Ratio): 888/8
EXIF GPS GPSImgDirectionRef (ASCII): M
EXIF GPS GPSLatitude (Ratio): [88, 8, 8888/888]
EXIF GPS GPSLatitudeRef (ASCII): N
EXIF GPS GPSLongitude (Ratio): [8, 88, 88888/8888]
EXIF GPS GPSLongitudeRef (ASCII): W
EXIF GPS GPSMapDatum (ASCII): WGS-84
EXIF GPS GPSMeasureMode (ASCII): 3
EXIF GPS GPSSpeed (Ratio): 88/88
EXIF GPS GPSSpeedRef (ASCII): K
EXIF GPS GPSStatus (ASCII): A
EXIF GPS GPSTimeStamp (Ratio): [14, 3, 6]
EXIF GPS GPSTrack (Ratio): 8888/88
EXIF GPS GPSTrackRef (ASCII): T
EXIF GPS GPSVersionID (Byte): [2, 3, 0, 0]
Image DateTime (ASCII): 2015:01:02 18:52:12
Image ExifOffset (Long): 888
Image GPSInfo (Long): 88888                             
Image Make (ASCII): SONY
Thumbnail DateTime (ASCII): 2014:09:13 16:03:05                              
Thumbnail Software (ASCII): DSC-HX20V v1.02
```

**Comment by andrewning** [comment]
Should be fixed by ee88628
