### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by NewtonsNerds** [andrewning/sortphotos#57]
Hi,
Fantastic module and I really want to be able to use it.

Windows 8 + Python 3.4
Module installed successfully
Both folders exist and 'origin' contains the images

**My command**
`python sortphotos.py -r D:\image-test\origin D:\image-test\destination`

**Error**
> FileNotFoundError: [WinError 2] The system cannot find the file specified

This is also a question on stackoverflow: 
http://stackoverflow.com/questions/32431521/how-to-run-python-module-andrewning-sortphotos-in-windows

Thanks heaps!
Siwei

**Comment by nekopep** [comment]
I think os.path.normpath(path) will help there.
Will try and will come back to you.

**Comment by dhagrow** [comment]
This actually happens because sortphotos tries to call Perl to run exiftool. Perl, of course is not installed on Windows by default. A pure Python alternative to exiftool would be the most ideal solution here.

**Comment by dsachau** [comment]
I had the same issue with Windows 7.  As per the advice in the other thread I was able to resolve the problem by installing Perl.  However, I also had to change the filename of exiftool to exiftool.pl, as described in the exiftool installation directions.  Then I had to change line 26 in sortphotos.py to match.  That resolved the FileNotFoundError. Unfortunately now I'm getting the following error.

c:\sortphotos-master\src>python sortphotos.py "c:\Users\Sachau\Pictures\test" "c
:\Users\Sachau\Pictures\sorted"
Preprocessing with ExifTool.  May take a while for a large number of files.
Traceback (most recent call last):
  File "sortphotos.py", line 297, in sortPhotos
    metadata = e.get_metadata(*args)
  File "sortphotos.py", line 210, in get_metadata
    return json.loads(self.execute(*args))
  File "sortphotos.py", line 196, in execute
    self.process.stdin.write(str.join("\n", args))
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sortphotos.py", line 487, in <module>
    main()
  File "sortphotos.py", line 484, in main
    args.use_only_tags, not args.silent)
  File "sortphotos.py", line 297, in sortPhotos
    metadata = e.get_metadata(*args)
  File "sortphotos.py", line 191, in __exit__
    self.process.stdin.write("-stay_open\nFalse\n")
TypeError: a bytes-like object is required, not 'str'

**Comment by winter98** [comment]
Just had the same problem as well and had to debug in pycharm to find the call to perl - shouldn't this either install by default or specify dependencies rather than expecting people to dig in and find this ?  As mentioned by dhagrow, perl not installed by default in windows (and even all linux distros?)

**Comment by arnaudvre** [comment]
Same issue here, ran in gitbash instead of windows CLI and problem gone. No other changes just "git clone" then "setup.py build" & "setup.py install"

Windows 10
Python 2.7.13 (to get around some of the Python3 related issues)

**Comment by cnsolari** [comment]
Here's my workaround to resolve the issues on using sortphotos on Windows 10 with Python 3.6

step 1: install windows git bash
step 2: "git clone" sortphotos github
step 3: cd into the sortphotos directory, and run "setup.py build" & "setup.py install" in git CMD
step 4: remove "encode('utf-8')"  on line 377 of the original sortphotos.py:
 # setup destination file
        dest_file = os.path.join(dest_file, filename.encode('utf-8')) --> dest_file = os.path.join(dest_file, filename)
step 5: running the scripts on git bash
python sortphotos.py D:/Old_SD/New D:/Old_SD/New/sorted --sort %Y/%b-%d --day-begins 4 -r

**Comment by gl4ssiest** [comment]
> 
> 
> Here's my workaround to resolve the issues on using sortphotos on Windows 10 with Python 3.6
> 
> step 1: install windows git bash
> step 2: "git clone" sortphotos github
> step 3: cd into the sortphotos directory, and run "setup.py build" & "setup.py install" in git CMD
> step 4: remove "encode('utf-8')" on line 377 of the original sortphotos.py:
> dest_file = os.path.join(dest_file, filename.encode('utf-8')) --> dest_file = os.path.join(dest_file, filename)
> step 5: running the scripts on git bash
> python sortphotos.py D:/Old_SD/New D:/Old_SD/New/sorted --sort %Y/%b-%d --day-begins 4 -r

After installed, sortphotos is included within PATH avaliable commands, so now step 5 can be done like this: (using unix directory syntaxis) `$sortphotos -r -t /drive/source_directory /drive/dest_directory `
