### ISSUE TITLE
Under windows % options are wrongly interpreted when using batch files

### ISSUE THREAD

**Issue by nekopep** [andrewning/sortphotos#62]
Hello andrew,
I've put the script in a bat file under windows and had to put %% instead of % to specify month/years etc, because % character is reserved for batch vars. (ex: %M%H%m -> %%M%%H%%m)
Since, it can be a useful feature to use with .bat file (tell user to click and it sorts), what other symbol can be used or which symbol do you think could be ok?
Is it acceptable for example to allow % and $ doing a .replace('$','%') on these parameters?

Laurent

**Comment by andrewning** [comment]
That's a good question, but I don't use Windows so I couldn't really say.  That's the only problematic character I've heard about from users so far.

By the way, I saw that you've contributed a whole bunch of really nice additions.  I definitely plan to pull that, but need to review and run some tests and realistically won't have time to do that until between semesters (e.g., late December).

**Comment by andrewning** [comment]
Oh, and issue #57, it was reported that Windows may have a problem with \ needing to be placed by \\ (see [here](http://stackoverflow.com/questions/32431521/how-to-run-python-module-andrewning-sortphotos-in-windows)).  I've not had a chance to find a Windows computer to verify, but that might be a good change to add to your bat file.

**Comment by nekopep** [comment]
Ha yeah, I didn't saw this one, it just an habit on windows :) never use / in command line :)
I think python has functions to workaround these corner case, something like normalize_path, woll take a look at it.

**Comment by nekopep** [comment]
No issue, I essentially patched your software to match my urgent sorting use case ;)
No urge there I plan to send you other patch for windows support. Because I saw 'utf-8' coding/decoding is messy there... :/

**Comment by jonsel087** [comment]
Hi- having the same issue, have tried using single \ and double \\ and am still getting the "[WinError 2] The system cannot find the file specified" error. Is there a fix for this? also tried os.path.normpath("") and not working as well

**Comment by andrewning** [comment]
What is the exact command you are using?

**Comment by jonsel087** [comment]
Thanks for getting back to me. I'm running Python 3.5 on a windows 10 machine. From the command line (from director of unzipped folder).

> python sortphotos.py -c C:\...\Pictures C:\...\sorted

Traceback (most recent call last):
  File "sortphotos.py", line 487, in <module>
    main()
  File "sortphotos.py", line 484, in main
    args.use_only_tags, not args.silent)
  File "sortphotos.py", line 294, in sortPhotos
    with ExifTool(verbose=verbose) as e:
  File "sortphotos.py", line 187, in __enter__
    stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by nekopep** [comment]
Have you installed perl on your windows?
sortphoto needs it.

**Comment by jonsel087** [comment]
I installed:
http://downloads.activestate.com/ActivePerl/releases/5.20.2.2002/ActivePerl-5.20.2.2002-MSWin32-x64-299195.msi

and am getting the same error. Could you maybe clarify which version of Perl or Perl packages are required?

I also tried to use a python version of the exiftool (which I'm guessing is what required Perl?), but was not sure of how to replace it in your script.

**Comment by andrewning** [comment]
I don't know of any pure python versions of exiftool.  I know of some python wrappers to exiftool, but they would still require Perl.

You can look at the instllations instructions offered by exiftool: http://www.sno.phy.queensu.ca/~phil/exiftool/install.html
Looks like they recommend the same place you downloaded.  Could be a path issue.  If you open a prompt can you open perl?

**Comment by jonsel087** [comment]
Hi Andrew, 

I have added the windows version of exiftool to my Windows folder and installed ActivePerl. I verified that both are working from the command line by running a test perl script and launching the exiftool. I also checked my system variables Path and saw Perl was added.

Unfortunately I'm still getting the same error as before.
FileNotFoundError: [WinError 2] The system cannot find the file specified;'

Regarding the path, could it possible be with my Python install location? For some reason Windows 10 installed it in a user folder instead of C:\ like normal. Either way, I made sure that the location of the Python35 folder is in the system path.

Looks like a great script, really hoping to use it!
