### ISSUE TITLE
German "Umlaute" lead to problem

### ISSUE THREAD

**Issue by deggler** [andrewning/sortphotos#74]
It seems like the German Umlaute in my files lead to an error, simmilar to: [this issue](https://github.com/andrewning/sortphotos/issues/47)

```
{ready}

[1/264]
Traceback (most recent call last):
  File "sortphotos.py", line 487, in <module>
    main()
  File "sortphotos.py", line 484, in main
    args.use_only_tags, not args.silent)
  File "sortphotos.py", line 318, in sortPhotos
    print('Source: ' + src_file)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 46: ordinal not in range(128)
```
i pulled the most recent release.

**Comment by eirism** [comment]
What python version are you using. I ran the script (python 2.7.11 and pulled the code today) with -t (test run) and a file name containing Ä. It did not crash.
