### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by dude0815** [andrewning/sortphotos#87]
If I start the Script, I receive the following message:

"File:FileInodeChangeDate": "2017:1No files to parse or invalid data
or 
Source: /srv/www/nc/data/dude/files/Fotos/Handy/Kamera/2017/08.07.2017/IMG_20170514_164852.jpg
Date/Time: 2002-12-08 12:00:00
Corresponding Tags: EXIF:CreateDate
Traceback (most recent call last):
  File "/opt/sortphotos-master/src/sortphotos.py", line 493, in <module>
    main()
  File "/opt/sortphotos-master/src/sortphotos.py", line 490, in main
    args.use_only_tags, not args.silent)
  File "/opt/sortphotos-master/src/sortphotos.py", line 375, in sortPhotos
    dest_file = os.path.join(dest_file, filename.encode('utf-8'))
  File "/usr/lib/python-exec/python3.5/../../../lib64/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python-exec/python3.5/../../../lib64/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
 
what's wrong and how can I fix it ?

**Comment by carylee** [comment]
I just encountered the same problem and fixed it by switching to python 2.7.

**Comment by andrewning** [comment]
updated for python 3
