### ISSUE TITLE
TypeError: Can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by ibrokemypie** [andrewning/sortphotos#92]
Hey, running your script and it crashed on me with the following error:
```
{ready}

[1/12392]
Source: ./Folder/2017/01-02/20170102-P1020026.dng
Date/Time: 2017-01-02 12:46:45
Corresponding Tags: MakerNotes:DateTimeUTC
Traceback (most recent call last):
  File "/usr/bin/sortphotos", line 11, in <module>
    load_entry_point('sortphotos==1.0', 'console_scripts', 'sortphotos')()
  File "/usr/lib/python3.6/site-packages/sortphotos-1.0-py3.6.egg/src/sortphotos.py", line 490, in main
    args.use_only_tags, not args.silent)
  File "/usr/lib/python3.6/site-packages/sortphotos-1.0-py3.6.egg/src/sortphotos.py", line 375, in sortPhotos
    dest_file = os.path.join(dest_file, filename.encode('utf-8'))
  File "/usr/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components

```

**Comment by gerenart** [comment]
Hi, I`m changed line 377 and it all worked.

dest_file = os.path.join(dest_file, str(filename.encode('utf-8'))[2: -1:])

**Comment by ReneFroger** [comment]
For others that are struggling with the same, just do `python2 [command]` instead of `pyhon [command]`.

Want to thank? You can help others to post your future solutions in boards.

**Comment by andrewning** [comment]
should hopefully work with either python 2 or 3 now

**Comment by b4tg5s** [comment]
This error persists.

`Python 3.9.1`
`This is perl 5, version 32, subversion 0 (v5.32.0) built for MSWin32-x64-multi-thread`
`Windows 10.0.19041 Build 19041`

```
Source: ....jpg
Date/Time: 2020-05-15 12:41:00
Corresponding Tags: File:FileModifyDate
Traceback (most recent call last):
  File "...\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "...\AppData\Local\Programs\Python\Python39\Scripts\sortphotos.exe\__main__.py", line 7, in <module>
  File "...\appdata\local\programs\python\python39\lib\site-packages\src\sortphotos.py", line 498, in main
    sortPhotos(args.src_dir, args.dest_dir, args.sort, args.rename, args.unknown_dir, args.recursive,
  File "...\appdata\local\programs\python\python39\lib\site-packages\src\sortphotos.py", line 376, in sortPhotos
    dest_file = os.path.join(dest_file, filename.encode('utf-8'))
  File "...\appdata\local\programs\python\python39\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "...\appdata\local\programs\python\python39\lib\genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by scotws** [comment]
I still have this problem as well with Ubuntu 20.04 LTS.

**Comment by matthiasbalke** [comment]
@gerenart can you explain me why your fix resolves the problem?

**Comment by eugenio-guarino** [comment]
> Hi, I`m changed line 377 and it all worked.
> 
> dest_file = os.path.join(dest_file, str(filename.encode('utf-8'))[2: -1:])

**as of january 2023 [for windows if you installed this through pip]:**

1. open directory C:\Users\Eugenio\AppData\Local\Programs\Python\Python311\Lib\site-packages\src\sortphotos.py
2. replace line 376 with gerenart's answer
